// Code generated by protoc-gen-go. DO NOT EDIT.
// source: servers/grpc.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Send2ClientReq struct {
	MessageId            string   `protobuf:"bytes,1,opt,name=messageId,proto3" json:"messageId,omitempty"`
	SendUserId           string   `protobuf:"bytes,2,opt,name=sendUserId,proto3" json:"sendUserId,omitempty"`
	ClientId             string   `protobuf:"bytes,3,opt,name=clientId,proto3" json:"clientId,omitempty"`
	Code                 int32    `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Data                 string   `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Send2ClientReq) Reset()         { *m = Send2ClientReq{} }
func (m *Send2ClientReq) String() string { return proto.CompactTextString(m) }
func (*Send2ClientReq) ProtoMessage()    {}
func (*Send2ClientReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_30edbedfc0173ed4, []int{0}
}

func (m *Send2ClientReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Send2ClientReq.Unmarshal(m, b)
}
func (m *Send2ClientReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Send2ClientReq.Marshal(b, m, deterministic)
}
func (m *Send2ClientReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Send2ClientReq.Merge(m, src)
}
func (m *Send2ClientReq) XXX_Size() int {
	return xxx_messageInfo_Send2ClientReq.Size(m)
}
func (m *Send2ClientReq) XXX_DiscardUnknown() {
	xxx_messageInfo_Send2ClientReq.DiscardUnknown(m)
}

var xxx_messageInfo_Send2ClientReq proto.InternalMessageInfo

func (m *Send2ClientReq) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *Send2ClientReq) GetSendUserId() string {
	if m != nil {
		return m.SendUserId
	}
	return ""
}

func (m *Send2ClientReq) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *Send2ClientReq) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Send2ClientReq) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Send2ClientReq) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type Send2ClientReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Send2ClientReply) Reset()         { *m = Send2ClientReply{} }
func (m *Send2ClientReply) String() string { return proto.CompactTextString(m) }
func (*Send2ClientReply) ProtoMessage()    {}
func (*Send2ClientReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_30edbedfc0173ed4, []int{1}
}

func (m *Send2ClientReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Send2ClientReply.Unmarshal(m, b)
}
func (m *Send2ClientReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Send2ClientReply.Marshal(b, m, deterministic)
}
func (m *Send2ClientReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Send2ClientReply.Merge(m, src)
}
func (m *Send2ClientReply) XXX_Size() int {
	return xxx_messageInfo_Send2ClientReply.Size(m)
}
func (m *Send2ClientReply) XXX_DiscardUnknown() {
	xxx_messageInfo_Send2ClientReply.DiscardUnknown(m)
}

var xxx_messageInfo_Send2ClientReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Send2ClientReq)(nil), "Send2ClientReq")
	proto.RegisterType((*Send2ClientReply)(nil), "Send2ClientReply")
}

func init() { proto.RegisterFile("servers/grpc.proto", fileDescriptor_30edbedfc0173ed4) }

var fileDescriptor_30edbedfc0173ed4 = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x50, 0xcd, 0x4e, 0x84, 0x30,
	0x10, 0xb6, 0xba, 0xbb, 0xba, 0xe3, 0xff, 0x9c, 0x9a, 0x8d, 0x31, 0x1b, 0x4e, 0x9c, 0x30, 0x81,
	0x37, 0x10, 0x2f, 0x5c, 0x21, 0x5e, 0xbc, 0x41, 0x3b, 0x21, 0x24, 0xd0, 0xd6, 0x96, 0x90, 0xf8,
	0x4e, 0x3e, 0xa4, 0x71, 0x22, 0x0a, 0xde, 0xbe, 0xbf, 0x7c, 0x99, 0xf9, 0x00, 0x03, 0xf9, 0x89,
	0x7c, 0x78, 0x6a, 0xbd, 0x53, 0x89, 0xf3, 0x76, 0xb4, 0xd1, 0xa7, 0x80, 0x9b, 0x8a, 0x8c, 0x4e,
	0xf3, 0xbe, 0x23, 0x33, 0x96, 0xf4, 0x8e, 0x0f, 0xb0, 0x1f, 0x28, 0x84, 0xba, 0xa5, 0x42, 0x4b,
	0x71, 0x14, 0xf1, 0xbe, 0xfc, 0x13, 0xf0, 0x11, 0x20, 0x90, 0xd1, 0xaf, 0x81, 0x7c, 0xa1, 0xe5,
	0x29, 0xdb, 0x0b, 0x05, 0x0f, 0x70, 0xa1, 0xb8, 0xaa, 0xd0, 0xf2, 0x8c, 0xdd, 0x5f, 0x8e, 0x08,
	0x1b, 0x65, 0x35, 0xc9, 0xcd, 0x51, 0xc4, 0xdb, 0x92, 0x31, 0x4a, 0x38, 0xff, 0x29, 0x97, 0x5b,
	0x8e, 0xcf, 0xf4, 0x3b, 0xad, 0xeb, 0xb1, 0x96, 0x3b, 0x96, 0x19, 0x47, 0x08, 0x77, 0xab, 0x6b,
	0x5d, 0xff, 0x91, 0xbe, 0xc0, 0x75, 0x6e, 0x87, 0xc1, 0x9a, 0x8a, 0xfc, 0xd4, 0x29, 0xc2, 0x0c,
	0x2e, 0x17, 0x21, 0xbc, 0x4d, 0xd6, 0x0f, 0x1e, 0xee, 0x93, 0xff, 0x1d, 0xd1, 0xc9, 0xf3, 0xd5,
	0x1b, 0xcc, 0xf3, 0xb8, 0xa6, 0xd9, 0xf1, 0x3a, 0xd9, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x26,
	0x60, 0xcf, 0x05, 0x33, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CommonServiceClient is the client API for CommonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommonServiceClient interface {
	Send2Client(ctx context.Context, in *Send2ClientReq, opts ...grpc.CallOption) (*Send2ClientReply, error)
}

type commonServiceClient struct {
	cc *grpc.ClientConn
}

func NewCommonServiceClient(cc *grpc.ClientConn) CommonServiceClient {
	return &commonServiceClient{cc}
}

func (c *commonServiceClient) Send2Client(ctx context.Context, in *Send2ClientReq, opts ...grpc.CallOption) (*Send2ClientReply, error) {
	out := new(Send2ClientReply)
	err := c.cc.Invoke(ctx, "/CommonService/Send2Client", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommonServiceServer is the server API for CommonService service.
type CommonServiceServer interface {
	Send2Client(context.Context, *Send2ClientReq) (*Send2ClientReply, error)
}

func RegisterCommonServiceServer(s *grpc.Server, srv CommonServiceServer) {
	s.RegisterService(&_CommonService_serviceDesc, srv)
}

func _CommonService_Send2Client_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Send2ClientReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonServiceServer).Send2Client(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CommonService/Send2Client",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonServiceServer).Send2Client(ctx, req.(*Send2ClientReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _CommonService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "CommonService",
	HandlerType: (*CommonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send2Client",
			Handler:    _CommonService_Send2Client_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "servers/grpc.proto",
}
